Traceback (most recent call last):
  File "dropbox_push.py", line 27, in <module>
    os.unlink("{0}/{1}".format(mypath, file))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/data/electoral/S01A004P272.PDF'
Traceback (most recent call last):
  File "dropbox_push.py", line 28, in <module>
    os.unlink("{0}/{1}".format(mypath, file))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/data/electoral/S01A013P056.PDF'
